### PR TITLE
React refactor playlists, closes #95

### LINKED ISSUE #95: playlists.js.jsx handleSubmit
-remove jQuery
-will probably require reformatting output of initial API call (value of @playlists) 
-setState and updating playlists to include the new playlist did not work because the new playlist is returned in a different format

### PR DESCRIPTION
**Pull request by AnnaCW**
This PR refactors view code related to the app's "create playlist" functionality. When converting views to React, I initially left the "append" piece on lines 11-16 of /playlists.js.jsx. Because of a difference in format between the playlists in the array initially returned by the Spotify API, and the format of the newly-created playlist returned after a successful POST to the API, it did not work to simply 'setState' to the updated playlists array. The addition on /playlists/js.jsx lines 4-6 fixes this.

### CODE REVIEW

**Comment by icorson3** [comment]
I think that your use of react is great! Nice job taking a risk and using this for a view. I would love to chat more about it and what you found powerful about the language.

**Review by icorson3 — COMMENTED** [review]
I think that your use of react is great! Nice job taking a risk and using this for a view. I would love to chat more about it and what you found powerful about the language.

**Comment by AnnaCW** [comment]
Thanks @icorson3! I would be happy to have a React chat.

File: app/assets/javascripts/components/playlists.js.jsx [hunk 1]
```diff
@@ -1,28 +1,26 @@
...
-      "<div class='col-md-4' id=" + playlist.name + ">" +
-        "<h4>" + playlist.name + "<h4>" +
-        "<iframe src='https://embed.spotify.com/?uri=" + playlist.uri + "&theme=white' width='300' height='380' frameborder='0' allowtransparency='true'></iframe>" +
-      "</div>"
-    )
   }
 
-  render () {
+  render() {
     return (
```
Comment (lucyfox4131) [inline app/assets/javascripts/components/playlists.js.jsx:19]: I'm liking all the clean up of extra spaces and semicolons and such.

Comment (AnnaCW) [reply app/assets/javascripts/components/playlists.js.jsx:19]: Thanks @lucyfox4131. Eslint!

File: app/assets/javascripts/components/playlists.js.jsx [hunk 2]
```diff
@@ -1,28 +1,26 @@
 class Playlists extends React.Component {
   constructor(props) {
     super();
+    var formattedPlaylists = props.playlists.map((playlist) => {
```
Comment (dalexj) [inline app/assets/javascripts/components/playlists.js.jsx:4]: I'd keep this to 1 line the function as: `(playlist) => playlist.table`

File: app/assets/javascripts/components/playlist.js.jsx [hunk 3]
```diff
@@ -1,14 +1,14 @@
...
 
   render() {
-    return(
-      <div className='col-md-4' id={this.props.playlist.table.name}>
-        <h4>{this.props.playlist.table.name}</h4>
-        <iframe src={"https://embed.spotify.com/?uri=" + this.props.playlist.table.uri + "&theme=white"} width="300" height="380" frameBorder="0" allowTransparency="true"></iframe>
+    return (
+      <div className='col-md-4' id={this.props.playlist.name}>
+        <h4>{this.props.playlist.name}</h4>
+        <iframe src={"https://embed.spotify.com/?uri=" + this.props.playlist.uri + "&theme=white"} width="300" height="380" frameBorder="0" allowTransparency="true"></iframe>
```
Comment (dalexj) [inline app/assets/javascripts/components/playlist.js.jsx:10]: can use the `<iframe />` shorthand instead of closing tag

File: app/assets/javascripts/components/all_playlists.js.jsx [hunk 4]
```diff
@@ -2,7 +2,7 @@ class AllPlaylists extends React.Component {
 
   render () {
     var playlists = this.props.playlists.map( (playlist) => {
-      return <Playlist key= {playlist.table.id} playlist={playlist} />
+      return <Playlist key= {playlist.id} playlist={playlist} />
```
Comment (dalexj) [inline app/assets/javascripts/components/all_playlists.js.jsx:5]: I find this sort of thing to be more readable if you just place the mapping inside the JSX where it goes instead of the variable, since you don't have to scroll back up to a variable, or make a variable for that matter. up to you

File: app/assets/javascripts/components/add_to_playlist.js.jsx [hunk 5]
```diff
@@ -48,10 +48,10 @@ class AddToPlaylist extends React.Component {
   }
 
   render() {
-    var playlists = this.state.playlists.map( (playlist) => {
-      return <PlaylistForAdd key={playlist.id} playlist={playlist} />
+    var playlists = this.state.playlists.map((playlist) => {
+      return <PlaylistForAdd key={playlist.id} playlist={playlist} />;
```
Comment (dalexj) [inline app/assets/javascripts/components/add_to_playlist.js.jsx:52]: same thing

File: app/assets/javascripts/components/add_to_playlist.js.jsx [hunk 6]
```diff
@@ -29,12 +29,12 @@ class AddToPlaylist extends React.Component {
...
       method: "PATCH",
-      data: {user_id: userId, playlist_id: playlistId, track_uri: trackUri },
+      data: {user_id: userId, playlist_id: playlistId, track_uri: trackUri},
       success: () => {
         $("#add-to-playlist").hide();
         $("#playlists-listing").hide();
-        $("#added-message").slideDown( () => {
-          setTimeout( () => {
+        $("#added-message").slideDown(() => {
+          setTimeout(() => {
```
Comment (dalexj) [inline app/assets/javascripts/components/add_to_playlist.js.jsx:37]: I think these would be a bit nicer if you have the time to spend to have react to do these instead of jquery
